const { logger } = require('../../utils/base/logger');

/**
 * GrootHelper - API Helper Methods
 * Auto-generated by API Helper Generator
 */
class GrootHelper {
    // Methods will be added here automatically

    /**
     * Get Task By Id
     * Auto-generated from cURL
     * GET http://staginternalapi.1mg.com/groot/v1/tasks/4796
     * 
     * @param {Object} apiContext - Playwright API context
     * @param {Object} payload - Request payload
     * @returns {Promise<Object>} API response
     */
    static async getTaskById(apiContext, payload) {
        logger.info(`🔸 Get Task By Id: ${JSON.stringify(payload).substring(0, 100)}`);

        const response = await apiContext.get('http://staginternalapi.1mg.com/groot/v1/tasks/4796', {
            data: payload
        });

        return response;
    }

}

module.exports = { GrootHelper };
